### ISSUE TITLE
Link to version 2021.1 not working and version 2021.2 missing

### ISSUE THREAD

**Issue by HenKlei** [pymor/docs#5]
I think [this line](https://github.com/pymor/docs/blob/b7cf4b6112bd12eeeb26796dbc3e2454a2596548/versions.json#L1) should be
```
{"2021.2": "2021-2-0", "2021.1": "2021-1-0", "2020.2": "2020.2.0", "2020.1": "2020.1.1", "2019.2": "2019.2.0", "development": "main"}
```
Otherwise, the link to version 2021.1 is not working and version 2021.2 does not appear in the list of available versions.

Is this list somehow generated automatically @renefritze or can we simply change it?

**Comment by renefritze** [comment]
You can change it directly, thanks!
